name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  flutter_keyboard_visibility: ^5.2.0
  geolocator: ^13.0.1
  custom_info_window: ^1.0.1
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.5.3
  shared_preferences: ^2.3.3
  firebase_database: ^10.4.0
  firebase_core: ^2.32.0
  firebase_core_web: ^2.18.1
  cloud_firestore: ^4.17.5
  flutter_typeahead: ^4.0.0
  firebase_auth: ^4.7.0
  flutter_svg: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/