// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs_XdjTldZnXX-Wcz0F7hPiD1DB3FxnQY',
    appId: '1:933477566768:ios:37c0d98b8e19ac624c60f5',
    messagingSenderId: '933477566768',
    projectId: 'yash-9dd33',
    databaseURL: 'https://yash-9dd33-default-rtdb.firebaseio.com',
    storageBucket: 'yash-9dd33.firebasestorage.app',
    iosClientId: '933477566768-3679l4ubdti0o30u7c0phhgj51fbcvi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEG79vjoQAQ2CKeUTIoORk2VSdldXF33E',
    appId: '1:933477566768:web:5fa44573d34c86fa4c60f5',
    messagingSenderId: '933477566768',
    projectId: 'yash-9dd33',
    authDomain: 'yash-9dd33.firebaseapp.com',
    databaseURL: 'https://yash-9dd33-default-rtdb.firebaseio.com',
    storageBucket: 'yash-9dd33.firebasestorage.app',
    measurementId: 'G-ZP9YZX8Q14',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs_XdjTldZnXX-Wcz0F7hPiD1DB3FxnQY',
    appId: '1:933477566768:ios:37c0d98b8e19ac624c60f5',
    messagingSenderId: '933477566768',
    projectId: 'yash-9dd33',
    databaseURL: 'https://yash-9dd33-default-rtdb.firebaseio.com',
    storageBucket: 'yash-9dd33.firebasestorage.app',
    iosClientId: '933477566768-3679l4ubdti0o30u7c0phhgj51fbcvi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB06EIUAQ2RnQ_xaorG-P-glnVg3ju1I1w',
    appId: '1:933477566768:android:59337aa2b78636304c60f5',
    messagingSenderId: '933477566768',
    projectId: 'yash-9dd33',
    databaseURL: 'https://yash-9dd33-default-rtdb.firebaseio.com',
    storageBucket: 'yash-9dd33.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEG79vjoQAQ2CKeUTIoORk2VSdldXF33E',
    appId: '1:933477566768:web:a1dccca8a35a932a4c60f5',
    messagingSenderId: '933477566768',
    projectId: 'yash-9dd33',
    authDomain: 'yash-9dd33.firebaseapp.com',
    databaseURL: 'https://yash-9dd33-default-rtdb.firebaseio.com',
    storageBucket: 'yash-9dd33.firebasestorage.app',
    measurementId: 'G-LVBR49ZHH5',
  );

}